export const codeVibeTheme = [
  "../public/assets/cards/codeVibesTheme/card_back.svg",
  "../public/assets/cards/codeVibesTheme/card (1).svg",
  "../public/assets/cards/codeVibesTheme/card (2).svg",
  "../public/assets/cards/codeVibesTheme/card (3).svg",
  "../public/assets/cards/codeVibesTheme/card (4).svg",
  "../public/assets/cards/codeVibesTheme/card (5).svg",
  "../public/assets/cards/codeVibesTheme/card (6).svg",
  "../public/assets/cards/codeVibesTheme/card (7).svg",
  "../public/assets/cards/codeVibesTheme/card (8).svg",
  "../public/assets/cards/codeVibesTheme/card (9).svg",
  "../public/assets/cards/codeVibesTheme/card (10).svg",
  "../public/assets/cards/codeVibesTheme/card (11).svg",
  "../public/assets/cards/codeVibesTheme/card (12).svg",
  "../public/assets/cards/codeVibesTheme/card (13).svg",
  "../public/assets/cards/codeVibesTheme/card (14).svg",
  "../public/assets/cards/codeVibesTheme/card (15).svg",
  "../public/assets/cards/codeVibesTheme/card (16).svg",
  "../public/assets/cards/codeVibesTheme/card (17).svg",
  "../public/assets/cards/codeVibesTheme/card (18).svg",
];

export const foodTheme = [
  "../public/assets/cards/foodTheme/card_back.svg",
  "../public/assets/cards/foodTheme/card (1).svg",
  "../public/assets/cards/foodTheme/card (2).svg",
  "../public/assets/cards/foodTheme/card (3).svg",
  "../public/assets/cards/foodTheme/card (4).svg",
  "../public/assets/cards/foodTheme/card (5).svg",
  "../public/assets/cards/foodTheme/card (6).svg",
  "../public/assets/cards/foodTheme/card (7).svg",
  "../public/assets/cards/foodTheme/card (8).svg",
  "../public/assets/cards/foodTheme/card (9).svg",
  "../public/assets/cards/foodTheme/card (10).svg",
  "../public/assets/cards/foodTheme/card (11).svg",
  "../public/assets/cards/foodTheme/card (12).svg",
  "../public/assets/cards/foodTheme/card (13).svg",
  "../public/assets/cards/foodTheme/card (14).svg",
  "../public/assets/cards/foodTheme/card (15).svg",
  "../public/assets/cards/foodTheme/card (16).svg",
  "../public/assets/cards/foodTheme/card (17).svg",
  "../public/assets/cards/foodTheme/card (18).svg",
];